# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.23)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS DeclarativeServices CppMicroServices)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target DeclarativeServices
add_library(DeclarativeServices SHARED IMPORTED)

set_target_properties(DeclarativeServices PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_variadic_templates;cxx_nullptr"
  INTERFACE_INCLUDE_DIRECTORIES "/home/pi/Documents/GarboTron/AtlasThingMiddleware_RPI-master/lib/CppMicroServices-development/compendium/DeclarativeServices/include;/home/pi/Documents/GarboTron/AtlasThingMiddleware_RPI-master/lib/compendium/DeclarativeServices/include;/home/pi/Documents/GarboTron/AtlasThingMiddleware_RPI-master/lib/include"
  INTERFACE_LINK_LIBRARIES "CppMicroServices;dl;usLogService;usServiceComponent"
)

# Create imported target CppMicroServices
add_library(CppMicroServices SHARED IMPORTED)

set_target_properties(CppMicroServices PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_variadic_templates;cxx_nullptr"
  INTERFACE_INCLUDE_DIRECTORIES "/home/pi/Documents/GarboTron/AtlasThingMiddleware_RPI-master/lib/CppMicroServices-development/framework/include;/home/pi/Documents/GarboTron/AtlasThingMiddleware_RPI-master/lib/framework/include;/home/pi/Documents/GarboTron/AtlasThingMiddleware_RPI-master/lib/include"
  INTERFACE_LINK_LIBRARIES "dl"
)

# Import target "DeclarativeServices" for configuration "Debug"
set_property(TARGET DeclarativeServices APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DeclarativeServices PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/pi/Documents/GarboTron/AtlasThingMiddleware_RPI-master/lib/lib/libDeclarativeServicesd.so.1.0.0"
  IMPORTED_SONAME_DEBUG "libDeclarativeServicesd.so.1.0.0"
  )

# Import target "CppMicroServices" for configuration "Debug"
set_property(TARGET CppMicroServices APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CppMicroServices PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/pi/Documents/GarboTron/AtlasThingMiddleware_RPI-master/lib/lib/libCppMicroServicesd.so.4.0.0"
  IMPORTED_SONAME_DEBUG "libCppMicroServicesd.so.4.0.0"
  )

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "usLogService" "usServiceComponent" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
